### ISSUE TITLE
vm lease hostname is not updated

### ISSUE THREAD

**Issue by chrodriguez** [MonolithProjects/terraform-libvirt-vm#14]
I've tried to create a new vm using the following file:

```
module "node" {
  source  = "MonolithProjects/vm/libvirt"
  version = ">= 1.9.0"

  vm_hostname_prefix  = "${var.vm_hostname_prefix}-worker-"
  base_volume_name    = libvirt_volume.base.name
  vm_count            = var.k8s_node_count
  bridge              = var.bridge
  memory              = var.k8s_node_memory
  vcpu                = var.k8s_node_vcpu
  pool                = var.pool
  system_volume       = var.disk_size

  dhcp                = true

  ssh_admin           = var.ssh_admin
  ssh_keys            = [
    chomp(file("~/.ssh/id_rsa.pub"))
    ]
  time_zone           = var.time_zone
}

output "master_ip" {
  value = module.master
}
```
All configurations are using default libvirt bridge using DHCP from dnsmasq. I've also configured libnss-libvirt and modifyed my nsswitch as required to resolve hostnames using libvirt. The problem arises when listing leases from virsh. When machine is just ceated, the following command `virsh  net-dhcp-leases` gives the following response:

```
Expiry Time           MAC address         Protocol   IP address           Hostname            Client ID or DUID
---------------------------------------------------------------------------------------------------------------------------------------------------------
 2022-03-29 20:18:54   52:54:00:46:73:e3   ipv4       192.168.122.158/24   ubuntu              ff:b5:5e:67:ff:00:02:00:00:ab:11:77:d8:05:b7:4a:d1:fc:a2
 2022-03-29 20:18:54   52:54:00:76:07:70   ipv4       192.168.122.150/24   ubuntu              ff:b5:5e:67:ff:00:02:00:00:ab:11:49:92:25:f3:32:cd:61:16
```
> I've created 2 vms with count in my example

To update leases, I've need to run inside vm the following command: **`sudo systemctl restart systemd-networkd`** and lease got updated. 

So I suggest to run a new command [inside runcmd](https://github.com/MonolithProjects/terraform-libvirt-vm/blob/main/templates/cloud_init.tpl#L13) as the following example:

```yaml
runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, qemu-guest-agent ]
  - [ systemctl, start, qemu-guest-agent ]
  - [ systemctl, restart, systemd-networkd ]
```

I don't know if this is a write solution, but after this, a new vm can be used from my system  resolver insantly, not waiting for lease expiration. May be, we can allow more lines to be added as custom runcmd....

What do you think?

**Comment by chrodriguez** [comment]
I've been waiting until lease expires, but the problem remains unitl reboot vm or run systemctl restart systemd-networkd

**Comment by MonolithProjects** [comment]
hi @chrodriguez, i agree. to have an option to add some additional custom commands to runcmd is a good idea. you can create a PR if you want.

**Comment by chrodriguez** [comment]
I'm currently working on this...
