### ISSUE TITLE
Default graphics type of spice incompatible with RHEL9.

### ISSUE THREAD

**Issue by paisley** [MonolithProjects/terraform-libvirt-vm#30]
This provider is unable to provision VMs using libvirt running on RHEL9 and its derivatives (CentOS 9, Rocky Linux 9, Alma Linux 9, etc.) due to the default graphics type being set to `spice` and [SPICE support being dropped](https://bugzilla.redhat.com/show_bug.cgi?id=2030592) in newer versions of RHEL. The graphics type of VNC (`vnc`) is compatible with these versions and shares the same options (`listen_type` and `autoport`) as the default spice graphics [specified in main.tf](https://github.com/MonolithProjects/terraform-libvirt-vm/blob/main/main.tf#L68).

Recommend changing this to a variable, leaving `spice` as the default, but also allowing `vnc` as an option. I will open a pull request with this proposed change shortly.

**Comment by MonolithProjects** [comment]
This was fixed in #31
