### ISSUE TITLE
Module incompatible with provider

### ISSUE THREAD

**Issue by oliverjkb** [MonolithProjects/terraform-libvirt-vm#7]
Currently, the provider `dmacvicar/libvirt` is available only from version 0.6.9 through 0.6.13 on the terraform.io registry.  
This causes `terraform init` to fail with error message `Could not retrieve the list of available versions for provider dmacvicar/libvirt: no available releases match the given constraints 0.6.3`.

Version constraints in main.tf should be bumped to one of the available versions, if possible.

**Comment by MonolithProjects** [comment]
Hi @oliverjkb, fix is on the way...

**Comment by oliverjkb** [comment]
Thanks! Much appreciated! :)
